# Generated by Django 4.2.2 on 2023-06-12 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='First name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last name')),
                ('national_code', models.CharField(max_length=10, unique=True, verbose_name='National code')),
                ('father_name', models.CharField(max_length=200, verbose_name='Father name')),
                ('shenasname_id', models.CharField(max_length=10, verbose_name='Shenasname id')),
                ('birthdate', models.DateField(verbose_name='Birth day')),
                ('address', models.TextField(verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
            },
        ),
        migrations.CreateModel(
            name='MobileLine',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('number', models.IntegerField(verbose_name='Number')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_lines', to='core.subscriber', verbose_name='Subscriber')),
            ],
            options={
                'verbose_name': 'Mobile line',
                'verbose_name_plural': 'Mobile line',
            },
        ),
    ]
