# Generated by Django 4.2.2 on 2023-06-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileline',
            name='number',
            field=models.CharField(max_length=11, unique=True, verbose_name='Number'),
        ),
    ]
